// Generated by CoffeeScript 1.6.1
(function() {

  $().ready(function() {
    return $(".box").click(function() {
      var name;
      return name = prompt("Start the quiz?");
    });
  });

}).call(this);
