// Generated by CoffeeScript 1.6.1
(function() {

  $().ready(function() {
    $(".box").click(function() {
      return prompt("Start the Quiz?");
    });
    return $(".button").click(function() {
      return alert("you clicked the yellow");
    });
  });

}).call(this);
